const AIPrompts: string[] = [
  `Generate a math word problem suitable for a Primary 5 student. The problem should be a word problem that requires understanding the text to solve. It should be solvable in one or two steps. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Generate a word problem about reading and writing whole numbers up to 10,000,000 appropriate for Primary 5. Use integers only. Keep problems short (one or two sentences). The correct_answer must be an integer numeral (no commas). No extra text. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Generate a 20 word problem that requires multiplying or dividing a whole number by 10, 100, 1000 or a multiple (e.g., 30, 400). Use integers so the final answer is an integer. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Create a word problem where dividing one whole number by another gives a quotient expressed as a fraction (not simplified to decimal). The correct_answer should be the numerical value as a proper fraction expressed as a decimal to two places if necessary. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Generate a word problem requiring multiplication of a proper or improper fraction by a whole number. The correct_answer should be given as a simplified fraction converted to a decimal if non-integer, rounded to two decimal places. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Produce a word problem that requires adding or subtracting mixed numbers. Return correct_answer as an improper fraction or as a decimal rounded to two places. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Create a one-sentence problem that requires multiplying or dividing a decimal (up to 3 dp) by 10, 100, or 1000. Ensure correct_answer is shown as a decimal with precise trailing zeros if needed. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Generate a word problem that converts a measurement from a smaller unit to a larger unit or vice versa (choose from km↔m, m↔cm, kg↔g, L↔mL). Keep numbers simple so the correct_answer is a decimal or integer consistent with Primary 5. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Create a word problem asking what percent a part is of a whole (simple numbers leading to an integer percent). The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Generate a problem about finding a discount or GST on a price. Keep numbers so correct_answer is a monetary value with two decimals. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Produce a word problem about rate expressed as amount per unit (e.g., cost per apple). Final_answer should be the rate or total or number of units and be an integer or decimal with two places. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Generate a problem where two of (rate, total amount, number of units) are given and the student must find the third. Keep values small and correct_answer numeric. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Generate a word problem that asks for the area of a triangle given base and height. Give base and height as integers; correct_answer is numeric area (use 0.5 × base × height). The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Create a word problem requiring the area of a composite figure made of rectangles and triangles. Keep dimensions integers and correct_answer an integer. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Produce a problem asking for the volume of liquid in a rectangular tank given length, width, and depth in cm; correct_answer should be in litres to one decimal place if needed (1 L = 1000 cm3). The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Create a word problem where the student must find an unknown angle on a straight line or at a point given one or two other angles. correct_answer should be an integer degree. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Generate a problem asking for an unknown angle in a triangle using angle sum rules or triangle properties (isosceles/equilateral/right-angled). correct_answer: integer degrees. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`,
  `Produce a word problem asking for an unknown angle or property in a parallelogram, rhombus, or trapezium without constructing extra lines; correct_answer integer degrees. The output must be a JSON object with two keys: "problem_text" (string) and "correct_answer" (number).`
];

export default AIPrompts;